CREATE TABLE CONTACT
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    client_id BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    "value" VARCHAR(255) NOT NULL,
    FOREIGN KEY (client_id) REFERENCES CLIENT (id) ON DELETE CASCADE
);